namespace Soundmates.IntegrationTests.Common;

[CollectionDefinition(TestConstants.IntegrationTestsCollectionName)]
public sealed class IntegrationTestsCollectionFixture : ICollectionFixture<CustomWebApplicationFactory>;
